palette = "terrafox"
format = """$username$hostname$directory$fill[$all](grey)$time$line_break$shell$character"""

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[shell]
fish_indicator = " "
nu_indicator = ">"
disabled = false

[fill]
symbol = '─'
style = '#2e383c'

[cmd_duration]
min_time = 10000

[time]
disabled = false
time_format = "%F %T"
style = "#859289"
format = '[$time]($style)'

[python]
symbol = "py "

[package]
symbol = " "
style = "#859289"

[git_branch]
symbol = " "

[palettes.terrafox]
grey = "#859289"
none = "#d3c6aa"
white = "#d3c6aa"
rosewater = "#e67e80"
flamingo = "#e67e80"
pink = "#d699b6"
mauve = "#d699b6"
maroon = "#e67e80"
peach = "#e69875"
sky = "#83c092"
sapphire = "#7fbbb3"
blue = "#7fbbb3"
lavender = "#7fbbb3"
text = "#d3c6aa"
subtext1 = "#d3c6aa"
subtext0 = "#c9b99a"
overlay2 = "#859289"
overlay1 = "#859289"
overlay0 = "#859289"
surface2 = "#374247"
surface1 = "#2e383c"
surface0 = "#2d353b"
base = "#272e33"
mantle = "#232a2e"
crust = "#1e2326"
background = "#272e33"
current_line = "#2e383c"
foreground = "#d3c6aa"
comment = "#859289"
cyan = "#83c092"
green = "#a7c080"
orange = "#e69875"
purple = "#d699b6"
red = "#e67e80"
yellow = "#dbbc7f"
